{{- if .Values.alembic.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values ) | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: {{- include "common.selectorLabels" ( dict "root" . "service" .Values ) | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.selectorLabels" ( dict "root" . "service" .Values ) | nindent 8 }}
    spec: {{- include "common.podConfig" ( dict "root" . "service" .Values.alembic ) | nindent 6 }}
      initContainers:
        - name: alembic
          {{- include "common.containerConfig" ( dict "root" . "container" .Values.alembic ) | nindent 10 }}
          args:
          {{- if .Values.alembic.mainStatic }}
            - bash
            - -c
            - alembic --name=main upgrade head && alembic --name=static upgrade head
          {{- else }}
            - alembic
            - --name=static
            - upgrade
            - head
          {{- end }}
      containers:
        - name: sleep
          image: busybox:latest
          args:
            - sleep
            - infinity
{{- end }}
