{{- if .Values.alembic.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.alembic ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.alembic ) | nindent 4 }}
  annotations: {{- toYaml .Values.alembic.annotations | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: {{- include "common.selectorLabels" ( dict "root" . "service" .Values.alembic ) | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.selectorLabels" ( dict "root" . "service" .Values.alembic ) | nindent 8 }}
    spec: {{- include "common.podConfig" ( dict "root" . "service" .Values.alembic ) | nindent 6 }}
      initContainers:
        - name: alembic
          {{- include "common.containerConfig" ( dict "root" . "container" .Values.alembic ) | nindent 10 }}
          args:
            - bash
            - -c
          {{- if .Values.alembic.mainStatic }}
            - alembic --name=main upgrade head && alembic --name=static upgrade head
          {{- else }}
            - alembic --name=static upgrade head
          {{- end }}
      containers:
        - name: sleep
          {{- include "common.containerConfig" ( dict "root" . "container" .Values.busybox ) | nindent 10 }}
          args:
            - tail
            - -f
            - /dev/null
{{- end }}
