apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geoportal.fullname" . }}-env
  labels:
{{ include "geoportal.labels" . | indent 4 }}
data:
  PGOPTIONS: "-c statement_timeout={{ .Values.postgresql.statementTimeout }}"
  GUNICORN_PARAMS: >-
    --bind=:8080
    --worker-class=gthread
    --threads={{ .Values.nbThreads }}
    --workers={{ if .Values.profiler.enabled }}1{{ else }}{{ .Values.nbProcesses }}{{ end }}
    {{- if gt .Values.nbProcesses 1.0 }}
    --max-requests=2000
    --max-requests-jitter=200
    {{- end }}
    --timeout={{ .Values.timeout }}
    {{- if .Values.statsd.enabled }}
    --statsd-host={{ .Values.statsd.url }}
    --statsd-prefix={{ .service }}.{{ .Release.Name }}
    {{- end }}
    {{- if .Values.gunicorn_config }}
        --config={{ .Values.gunicorn_config }}
    {{- end }}
    --worker-tmp-dir=/dev/shm
  SENTRY_URL: https://{{ .Values.sentry.key }}@{{ .Values.sentry.hostname }}/{{ .Values.sentry.project }}
  TILECLOUDCHAIN_INTERNAL_URL: http://{{ include "geoportal.fullname" . }}-tilecloudchain/
  GEOPORTAL_INTERNAL_URL: http://{{ include "geoportal.fullname" . }}-geoportal/
  MAPSERVER_URL: http://{{ include "geoportal.fullname" . }}-mapserver/
  QGISSERVER_URL: http://{{ include "geoportal.fullname" . }}-qgisserver/
  GEOPORTAL_INTERNAL_HOST: {{ include "geoportal.fullname" . }}-geoportal
  TILECLOUDCHAIN_INTERNAL_HOST: {{ include "geoportal.fullname" . }}-tilecloudchain
  VISIBLE_WEB_HOST: {{ (index .Values.ingress.hosts 0).host }}
  VISIBLE_ENTRY_POINT: {{ .Values.entrypoint }}
  VISIBLE_WEB_HOST_RE_ESCAPED: {{ replace "." "\\." (index .Values.ingress.hosts 0).host | quote }}
  VISIBLE_ENTRY_POINT_RE_ESCAPED: {{ replace "." "\\." .Values.entrypoint | quote }}
  MAPSERVER_DATA_SUBSELECT: >
    SELECT ST_Collect(ra.area)
    FROM {{ .Values.postgresql.schema }}.restrictionarea AS ra,
    {{ .Values.postgresql.schema }}.role_restrictionarea AS rra,
    {{ .Values.postgresql.schema }}.layer_restrictionarea AS lra,
    {{ .Values.postgresql.schema }}.treeitem AS la
    WHERE rra.role_id in (%role_ids%) AND rra.restrictionarea_id = ra.id
    AND lra.restrictionarea_id = ra.id AND lra.layer_id = la.id AND la.name =
  MAPSERVER_DATA_NOAREA_SUBSELECT: >
    SELECT rra.role_id
    FROM {{ .Values.postgresql.schema }}.restrictionarea AS ra,
    {{ .Values.postgresql.schema }}.role_restrictionarea AS rra,
    {{ .Values.postgresql.schema }}.layer_restrictionarea AS lra,
    {{ .Values.postgresql.schema }}.treeitem AS la
    WHERE rra.restrictionarea_id = ra.id AND lra.restrictionarea_id = ra.id
    AND lra.layer_id = la.id AND la.name =
  MAPSERVER_JOIN_TABLES: >
    {{ .Values.postgresql.schema }}.restrictionarea AS ra,
    {{ .Values.postgresql.schema }}.role_restrictionarea AS rra,
    {{ .Values.postgresql.schema }}.layer_restrictionarea AS lra,
    {{ .Values.postgresql.schema }}.treeitem AS la
  MAPSERVER_JOIN_WHERE: >
    rra.role_id in (%role_ids%) AND rra.restrictionarea_id = ra.id AND
    lra.restrictionarea_id = ra.id AND lra.layer_id = la.id AND la.name =
