{{- if .Values.dbstats.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.dbstats ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.dbstats ) | nindent 4 }}
spec:
  schedule: "{{ mod (regexReplaceAll "[a-f]+" (printf "%s-%s" .Release.Namespace .Release.Name | sha256sum) "" | trunc 5) 60 }} * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels: {{- include "common.selectorLabels" ( dict "root" . "service" .Values.dbstats ) | nindent 12 }}
        spec: {{ include "common.podConfig" ( dict "root" . "service" .Values.dbstats ) | nindent 10 }}
          containers:
            - name: dbstats
              {{- include "common.containerConfig" ( dict "root" . "container" .Values.dbstats ) | nindent 14 }}
              args:
                - bash
                - -ce
                - |
                  TARGET="--prometheus_instance={{ .Release.Namespace }}-{{ template "common.fullname" ( dict "root" . "service" .Values ) }} --prometheus_url={{ .Values.prometheus.url }}"
                  export STATSD_TAG_DB=$(PGDATABASE)
                  c2cwsgiutils-stats-db \
                    --db=postgresql://$(PGUSER):$(PGPASSWORD)@$(PGHOST):5432/$(PGDATABASE) \
                  {{- range .Values.dbstats.schemas }}
                  --schema={{ . }} \
                  {{- end }}
                    ${TARGET}
                  {{- range .Values.dbstats.extraDBs  }}
                  TARGET="--prometheus_instance={{ $.Release.Namespace }}-{{ template "common.fullname" ( dict "root" $ "service" $.Values ) }}-{{ .database }} --prometheus_url={{ $.Values.dbstats.prometheus }}"
                  export STATSD_TAG_DB="{{ .database }}"
                  c2cwsgiutils-stats-db \
                    --db=postgresql://{{ .user | default "$(PGUSER)" }}:{{ .password | default "$(PGPASSWORD)" }}@{{ .host | default "$(PGHOST)" }}:5432/{{ .database }} \
                    --verbosity WARNING \
                    {{- range .schemas }}
                    --schema={{ . }} \
                    {{- end }}
                    ${TARGET}
                  {{- end }}
{{- end }}
