apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoportal.fullname" . }}
  labels:
{{ include "geoportal.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if .Values.prometheus }}
    - port: 80
      targetPort: prometheus
      protocol: TCP
      name: prometheus
{{- end }}
  selector:
    {{- include "geoportal.selectorLabels" . | nindent 4 }}
