{{- if .Values.tools.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.tools ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.tools ) | nindent 4 }}
  {{- with .Values.tools.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: {{- include "common.selectorLabels" ( dict "root" . "service" .Values.tools ) | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.selectorLabels" ( dict "root" . "service" .Values.tools ) | nindent 8 }}
      {{- range $key, $value := .Values.tools.podLabels }}
        {{ $key }}: {{ $value }}
      {{- end }}
      {{- with .Values.tools.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec: {{- include "common.podConfig" ( dict "root" . "service" .Values.tools ) | nindent 6 }}
      containers:
        - name: tools
          {{- include "common.containerConfig" ( dict "root" . "container" .Values.tools ) | nindent 10 }}
          args:
           - sleep
           - infinity{{- end }}
