#!/bin/bash -eu

kubectl config set-context --current --namespace=default

echo ::group::Events
kubectl get events
echo ::endgroup::

echo ::group::Continers
kubectl get containers --output=wide
echo ::endgroup::

echo ::group::Pods
kubectl get pods --output=wide
echo ::endgroup::

for name in $(kubectl get pods --output=name)
do
  echo ::group::$name: Describe
  kubectl describe $name
  echo ::endgroup::

  echo ::group::$name: Logs
  kubectl logs $name
  echo ::endgroup::
done
